#!/bin/bash

# Define the environmental variable
ENV_VAR="GOOGLE_APPLICATION_CREDENTIALS=~/fluentflow-practice-222333f84ffc.json"

# Check if the variable already exists in .bashrc
if ! grep -q "$ENV_VAR" ~/.bashrc; then
    # Add the variable to .bashrc
    echo "$ENV_VAR" >> ~/.bashrc
    echo "Environmental variable added to .bashrc"
else
    echo "Environmental variable already exists in .bashrc"
fi
# achieves export GOOGLE_APPLICATION_CREDENTIALS=~/fluentflow-practice-222333f84ffc.json but permanently
